import path from "node:path";
import fs from "node:fs";
import { writeFileDeep, info } from "./utils.js";

export function initBrain(projectDir: string) {
  const brain = path.join(projectDir, "swamr", "brain");

  if (fs.existsSync(brain) && fs.readdirSync(brain).length > 1) {
    info("Obsidian brain already exists, skipping");
    return;
  }

  const dirs = [
    "00-project",
    "01-planning",
    "01-planning/decisions",
    "01-planning/domains",
    "02-foundation",
    "03-build",
    "03-build/task-outputs",
    "03-build/issues",
    "03-build/checkpoints",
    "04-testing",
    "05-security",
    "05-legal",
    "06-launch",
    "templates",
    ".obsidian",
  ];
  for (const d of dirs) {
    fs.mkdirSync(path.join(brain, d), { recursive: true });
  }

  writeFileDeep(
    path.join(brain, "index.md"),
    `# Swamr Brain — Map of Content

> The second brain for your agent swarm. Agents read from and write to this vault so no context is ever lost across phases or sessions. The orchestrator regenerates the live status section below after every wave.

## Quick Links
- [[00-project/overview|Project Overview]]
- [[00-project/tech-stack|Tech Stack]]
- [[00-project/architecture|Architecture]]
- [[00-project/existing-state|Existing State]] (adopt mode)
- [[01-planning/task-tree|Task Tree]]
- [[01-planning/requirements|Requirements]]
- [[01-planning/domains/_index|Planning Domains]]
- [[03-build/phase-log|Build Log]]

## Phases
- [[02-foundation/phase-summary|Foundation]]
- [[03-build/phase-log|Build]]
- [[04-testing/phase-summary|Testing (E2E)]]
- [[05-security/phase-summary|Security Hardening]]
- [[05-legal/phase-summary|Legal Compliance]]
- [[06-launch/handoff|Launch / Handoff]]

## How This Works
1. The orchestrator initializes this vault when a build starts
2. Every agent reads relevant notes before starting a task AND adopts its specialist persona
3. Every agent writes a task output note (with [[wikilinks]]) when done
4. Quality gates + checkpoint agents verify each wave and file fix tasks for any bug
5. Phase summaries capture carry-forward context
6. You can browse this vault in Obsidian to watch progress in real-time

<!-- SWAMR:LIVE-STATUS:START -->
## Live Status
- **Phase**: Not started
- **Tasks**: 0/0
- **Last Updated**: —
<!-- SWAMR:LIVE-STATUS:END -->

## Task Outputs (dataview)
\`\`\`dataview
TABLE status, agent, date
FROM "03-build/task-outputs"
SORT date DESC
\`\`\`
`
  );

  writeFileDeep(
    path.join(brain, "01-planning/domains/_index.md"),
    `# Planning Domains

> The lead architect splits the system into domains during hierarchical planning. Each domain gets its own sub-planner that writes a note here and a slice of the task list.

| Domain | Specialist | Focus |
|--------|-----------|-------|
| — | — | — |
`
  );

  writeFileDeep(
    path.join(brain, "00-project/overview.md"),
    `# Project Overview

> This file is populated by the orchestrator when a build begins.

## Name
[TBD]

## Description
[TBD]

## Goals
- [TBD]

## Constraints
- [TBD]
`
  );

  writeFileDeep(
    path.join(brain, "00-project/tech-stack.md"),
    `# Tech Stack

> Populated by the orchestrator during planning.

| Layer | Choice | Rationale |
|-------|--------|-----------|
| Frontend | TBD | — |
| Backend | TBD | — |
| Database | TBD | — |
| Auth | TBD | — |
| Hosting | TBD | — |
`
  );

  writeFileDeep(
    path.join(brain, "00-project/architecture.md"),
    `# Architecture

> Populated by the orchestrator during planning. Updated as decisions are made.

## System Overview
[TBD]

## Data Flow
[TBD]

## Key Decisions
[See [[01-planning/decisions/]] for Architecture Decision Records]
`
  );

  writeFileDeep(
    path.join(brain, "00-project/glossary.md"),
    `# Glossary

> Domain terms and definitions. Agents add to this as they encounter new terms.

| Term | Definition |
|------|-----------|
| — | — |
`
  );

  writeFileDeep(
    path.join(brain, "01-planning/task-tree.md"),
    `# Task Tree

> Generated by @swamr-planner. Master list of all tasks with dependencies.

## Phase 1: Foundation
[TBD]

## Phase 2: Build
[TBD]

## Phase 3: Testing
[TBD]

## Phase 4: Hardening
[TBD]

## Phase 5: Launch
[TBD]
`
  );

  writeFileDeep(
    path.join(brain, "01-planning/requirements.md"),
    `# Requirements

> Detailed requirements breakdown. Populated during planning.

## Functional Requirements
- [TBD]

## Non-Functional Requirements
- [TBD]

## Out of Scope
- [TBD]
`
  );

  writeFileDeep(
    path.join(brain, "01-planning/risk-register.md"),
    `# Risk Register

| Risk | Impact | Likelihood | Mitigation |
|------|--------|-----------|-----------|
| — | — | — | — |
`
  );

  writeFileDeep(
    path.join(brain, "03-build/phase-log.md"),
    `# Build Phase Log

> Running log of build progress. Updated by the orchestrator after each task.

## Timeline
| Date | Task | Agent | Status | Notes |
|------|------|-------|--------|-------|
| — | — | — | — | — |
`
  );

  // Templates
  writeFileDeep(
    path.join(brain, "templates/task-output.md"),
    `---
task_id: [ID]
agent: [agent-slug]
phase: [phase number]
status: completed
date: [ISO date]
files_changed: []
---

# Task: [Description]

## What Was Built
[1-3 sentence summary]

## Key Decisions
- [Decision]: [Why]

## Dependencies Created
- [What depends on this and why]

## Context for Next Agent
[What the next agent working in this area needs to know]

## Files Reference
| File | Purpose |
|------|---------|
| \`path/to/file\` | [what it does] |

## Open Questions
- [Anything unresolved]
`
  );

  writeFileDeep(
    path.join(brain, "templates/decision-record.md"),
    `---
id: ADR-[NNN]
title: [Decision Title]
status: accepted
date: [ISO date]
agent: [agent-slug]
---

# ADR-[NNN]: [Decision Title]

## Context
[What prompted this decision]

## Decision
[What we decided]

## Rationale
[Why we chose this over alternatives]

## Alternatives Considered
1. [Alternative 1] — rejected because [reason]
2. [Alternative 2] — rejected because [reason]

## Consequences
- [Positive consequence]
- [Trade-off or negative consequence]
`
  );

  writeFileDeep(
    path.join(brain, "templates/phase-summary.md"),
    `---
phase: [number]
name: [phase name]
completed: [ISO date]
tasks_completed: [count]
tasks_failed: [count]
---

# Phase [N] Summary: [Name]

## What Was Accomplished
[Summary]

## Architecture State
[Current state of the codebase]

## Carry-Forward Context
[Critical info the next phase needs — this prevents context loss]

## Known Issues
- [Issue 1]

## Metrics
- Tasks completed: X/Y
- QA pass rate: Z%
`
  );

  // Obsidian app config
  writeFileDeep(
    path.join(brain, ".obsidian/app.json"),
    JSON.stringify(
      {
        showLineNumber: true,
        strictLineBreaks: false,
        readableLineLength: true,
      },
      null,
      2
    )
  );

  info("Created Obsidian brain vault at swamr/brain/");
}
